<?php
session_start();
require_once "../../auth/auth_check.php";
require_once "../../auth/database.php";
require_once "ClinicReportService.php";

$database = Database::getInstance();
$db = $database->getConnection();

if ($db === null) {
    echo '<div class="alert alert-danger">Database connection failed</div>';
    exit;
}

$reportService = new ClinicReportService($db);
$report_id = $_GET['report_id'] ?? '';

if (empty($report_id)) {
    echo '<div class="alert alert-warning">Report ID is required</div>';
    exit;
}

$report = $reportService->getReport($report_id);

if (!$report) {
    echo '<div class="alert alert-danger">Report not found</div>';
    exit;
}

$report_data = json_decode($report['report_data'], true);
?>

<div class="report-view p-3">
    <div class="row mb-4">
        <div class="col-sm-6">
            <h5><strong>Report ID:</strong> <?= htmlspecialchars($report['report_id']) ?></h5>
            <p class="mb-1"><strong>Type:</strong> <span class="badge badge-info"><?= htmlspecialchars($report['report_type']) ?></span></p>
            <p class="mb-0"><strong>Generated By:</strong> <?= htmlspecialchars($report['generated_by']) ?></p>
        </div>
        <div class="col-sm-6 text-sm-right">
            <p class="mb-1 text-muted"><strong>Date Generated:</strong> <?= date('M d, Y h:i A', strtotime($report['created_at'])) ?></p>
            <p class="mb-0 text-muted"><strong>Period:</strong> <?= date('M d, Y', strtotime($report['start_date'])) ?> to <?= date('M d, Y', strtotime($report['end_date'])) ?></p>
        </div>
    </div>

    <hr>

    <?php if (isset($report_data['summary']) && !empty($report_data['summary'])): ?>
        <div class="mt-4">
            <h6 class="font-weight-bold text-primary mb-3"><i class="fas fa-th-list mr-2"></i>Summary Statistics</h6>
            <div class="row">
                <?php foreach ($report_data['summary'] as $key => $value): ?>
                    <div class="col-md-3 col-6 mb-3">
                        <div class="card bg-light border-0 shadow-none mb-0 h-100">
                            <div class="card-body py-3 px-2 text-center">
                                <small class="text-uppercase text-muted d-block mb-1"><?= ucwords(str_replace('_', ' ', $key)) ?></small>
                                <span class="h5 font-weight-bold mb-0"><?= is_numeric($value) ? number_format($value) : htmlspecialchars($value) ?></span>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>

    <?php if (isset($report_data['details']['visits']) && !empty($report_data['details']['visits'])): ?>
        <div class="mt-4">
            <h6 class="font-weight-bold text-primary mb-3"><i class="fas fa-user-md mr-2"></i>Patient Visits Details</h6>
            <div class="table-responsive">
                <table class="table table-sm table-hover table-bordered mb-0">
                    <thead class="bg-light">
                        <tr>
                            <th>Time</th>
                            <th>Patient Name</th>
                            <th>Chief Complaint</th>
                            <th>Diagnosis</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($report_data['details']['visits'] as $visit): ?>
                            <tr>
                                <td><?= isset($visit['visit_time']) ? date('h:i A', strtotime($visit['visit_time'])) : (isset($visit['visit_date']) ? date('h:i A', strtotime($visit['visit_date'])) : 'N/A') ?></td>
                                <td><?= htmlspecialchars(($visit['first_name'] ?? '') . ' ' . ($visit['last_name'] ?? '')) ?></td>
                                <td><?= htmlspecialchars($visit['chief_complaint'] ?? 'N/A') ?></td>
                                <td><?= htmlspecialchars($visit['diagnosis'] ?? 'N/A') ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    <?php endif; ?>

    <?php if (isset($report_data['trends']['common_diagnoses']) && !empty($report_data['trends']['common_diagnoses'])): ?>
        <div class="mt-4">
            <h6 class="font-weight-bold text-primary mb-3"><i class="fas fa-chart-pie mr-2"></i>Common Diagnoses</h6>
            <div class="row">
                <?php foreach ($report_data['trends']['common_diagnoses'] as $diag): ?>
                    <div class="col-md-6 mb-2">
                        <div class="d-flex justify-content-between align-items-center p-2 border rounded bg-white">
                            <span><?= htmlspecialchars($diag['diagnosis'] ?? 'N/A') ?></span>
                            <span class="badge badge-primary badge-pill px-3"><?= $diag['count'] ?? 0 ?> cases</span>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>

    <?php if (isset($report_data['trends']['medicine_usage']) && !empty($report_data['trends']['medicine_usage'])): ?>
        <div class="mt-4">
            <h6 class="font-weight-bold text-primary mb-3"><i class="fas fa-pills mr-2"></i>Medicine Usage Breakdown</h6>
            <div class="table-responsive">
                <table class="table table-sm table-hover table-bordered mb-0">
                    <thead class="bg-light">
                        <tr>
                            <th>Medicine Name</th>
                            <th>Units Used</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($report_data['trends']['medicine_usage'] as $usage): ?>
                            <tr>
                                <td><?= htmlspecialchars($usage['medicine_name'] ?? 'N/A') ?></td>
                                <td><?= number_format($usage['total_used'] ?? 0) ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    <?php endif; ?>

    <?php if (isset($report_data['data']['summary'])): ?>
        <div class="mt-4">
            <h6 class="font-weight-bold text-primary mb-3"><i class="fas fa-chart-bar mr-2"></i>Report Summary</h6>
            <div class="row">
                <?php foreach ($report_data['data']['summary'] as $key => $value): ?>
                    <div class="col-md-3 col-6 mb-3">
                        <div class="card bg-light border-0 shadow-none mb-0 h-100">
                            <div class="card-body py-3 px-2 text-center">
                                <small class="text-uppercase text-muted d-block mb-1"><?= ucwords(str_replace('_', ' ', $key)) ?></small>
                                <span class="h5 font-weight-bold mb-0"><?= is_numeric($value) ? number_format($value) : htmlspecialchars($value) ?></span>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    <?php endif; ?>

    <div class="modal-footer px-0 pb-0 mt-4 border-top-0">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <a href="generate_report_pdf.php?report_id=<?= $report['report_id'] ?>" class="btn btn-success" target="_blank">
            <i class="fas fa-file-pdf mr-1"></i> Download PDF
        </a>
    </div>
</div>
