<?php
session_start();
require_once "../auth/auth_check.php";
require_once "../auth/database.php";
require_once "services/ClinicReportService.php";

$database = Database::getInstance();
$db = $database->getConnection();

if ($db === null || !isset($_GET['report_id'])) {
    die("Invalid request.");
}

$reportService = new ClinicReportService($db);
$report = $reportService->getReport($_GET['report_id']);

if (!$report) {
    die("Report not found.");
}

$report_data = json_decode($report['report_data'], true);
$filename = $report['report_id'] . ".html";

// Set headers for HTML download
header('Content-Type: text/html; charset=utf-8');
header('Content-Disposition: attachment; filename=' . $filename);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BCP Clinic Report - <?= htmlspecialchars($report['report_id']) ?></title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 1000px; margin: 0 auto; padding: 20px; }
        .header { text-align: center; border-bottom: 2px solid #003399; padding-bottom: 10px; margin-bottom: 30px; }
        .header h1 { color: #003399; margin: 0; }
        .report-info { display: flex; justify-content: space-between; margin-bottom: 30px; background: #f8f9fa; padding: 15px; border-radius: 8px; }
        .section-title { color: #003399; border-left: 5px solid #003399; padding-left: 10px; margin: 30px 0 15px 0; }
        .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 30px; }
        .stat-card { background: #fff; border: 1px solid #dee2e6; padding: 15px; border-radius: 8px; text-align: center; }
        .stat-card small { color: #6c757d; text-transform: uppercase; font-size: 0.8rem; }
        .stat-card div { font-size: 1.5rem; font-weight: bold; color: #333; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        th, td { border: 1px solid #dee2e6; padding: 12px; text-align: left; }
        th { background-color: #f8f9fa; color: #333; }
        tr:nth-child(even) { background-color: #fafafa; }
        .footer { text-align: center; margin-top: 50px; font-size: 0.9rem; color: #6c757d; border-top: 1px solid #dee2e6; padding-top: 20px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>BCP CLINIC MANAGEMENT SYSTEM</h1>
        <p>Official Clinic Report</p>
    </div>

    <div class="report-info">
        <div>
            <p><strong>Report ID:</strong> <?= htmlspecialchars($report['report_id']) ?></p>
            <p><strong>Type:</strong> <?= htmlspecialchars($report['report_type']) ?></p>
            <p><strong>Period:</strong> <?= date('M d, Y', strtotime($report['start_date'])) ?> to <?= date('M d, Y', strtotime($report['end_date'])) ?></p>
        </div>
        <div style="text-align: right;">
            <p><strong>Generated By:</strong> <?= htmlspecialchars($report['generated_by']) ?></p>
            <p><strong>Date Generated:</strong> <?= date('M d, Y h:i A', strtotime($report['created_at'])) ?></p>
        </div>
    </div>

    <?php if (isset($report_data['summary'])): ?>
        <h2 class="section-title">Summary Statistics</h2>
        <div class="stats-grid">
            <?php foreach ($report_data['summary'] as $key => $value): ?>
                <div class="stat-card">
                    <small><?= ucwords(str_replace('_', ' ', $key)) ?></small>
                    <div><?= number_format($value) ?></div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php if (isset($report_data['details']['visits']) && !empty($report_data['details']['visits'])): ?>
        <h2 class="section-title">Patient Visit Details</h2>
        <table>
            <thead>
                <tr>
                    <th>Time</th>
                    <th>Patient Name</th>
                    <th>Chief Complaint</th>
                    <th>Diagnosis</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($report_data['details']['visits'] as $visit): ?>
                    <tr>
                        <td><?= isset($visit['visit_time']) ? date('h:i A', strtotime($visit['visit_time'])) : (isset($visit['visit_date']) ? date('h:i A', strtotime($visit['visit_date'])) : 'N/A') ?></td>
                        <td><?= htmlspecialchars(($visit['first_name'] ?? '') . ' ' . ($visit['last_name'] ?? '')) ?></td>
                        <td><?= htmlspecialchars($visit['chief_complaint'] ?? 'N/A') ?></td>
                        <td><?= htmlspecialchars($visit['diagnosis'] ?? 'N/A') ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>

    <?php if (isset($report_data['trends']['common_diagnoses']) && !empty($report_data['trends']['common_diagnoses'])): ?>
        <h2 class="section-title">Top Diagnoses</h2>
        <table>
            <thead>
                <tr>
                    <th>Diagnosis</th>
                    <th>Cases Count</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($report_data['trends']['common_diagnoses'] as $diag): ?>
                    <tr>
                        <td><?= htmlspecialchars($diag['diagnosis'] ?? 'N/A') ?></td>
                        <td><?= $diag['count'] ?? 0 ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>

    <?php if (isset($report_data['trends']['medicine_usage']) && !empty($report_data['trends']['medicine_usage'])): ?>
        <h2 class="section-title">Medicine Usage Breakdown</h2>
        <table>
            <thead>
                <tr>
                    <th>Medicine Name</th>
                    <th>Units Used</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($report_data['trends']['medicine_usage'] as $usage): ?>
                    <tr>
                        <td><?= htmlspecialchars($usage['medicine_name'] ?? 'N/A') ?></td>
                        <td><?= number_format($usage['total_used'] ?? 0) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>

    <div class="footer">
        <p>&copy; <?= date('Y') ?> BCP Clinic Management System. All rights reserved.</p>
        <p>This is a computer-generated document.</p>
    </div>
</body>
</html>
