<?php
require_once "../auth/auth_check.php";
require_once "../auth/database.php";
require_once "core/BaseModel.php";
require_once "services/ClinicReportService.php";
require_once "lib/fpdf/fpdf.php";

if (!isset($_GET['report_id'])) {
    die("Report ID is required.");
}

$report_id = $_GET['report_id'];
$database = Database::getInstance();
$db = $database->getConnection();
$clinic_report = new ClinicReportService($db);

$report = $clinic_report->getReport($report_id);
if (!$report) {
    die("Report not found.");
}

$reportData = json_decode($report['report_data'], true);

class ReportPDF extends FPDF {
    function Header() {
        $this->SetFont('Arial', 'B', 15);
        $this->Cell(0, 10, 'BCP BULACAN CLINIC SYSTEM', 0, 1, 'C');
        $this->SetFont('Arial', '', 12);
        $this->Cell(0, 7, 'Clinic Management Report', 0, 1, 'C');
        $this->Ln(10);
    }

    function Footer() {
        $this->SetY(-15);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(0, 10, 'Page ' . $this->PageNo() . '/{nb}', 0, 0, 'C');
        $this->Cell(0, 10, 'Generated on: ' . date('Y-m-d H:i:s'), 0, 0, 'R');
    }

    function SectionHeader($label) {
        $this->SetFillColor(230, 230, 230);
        $this->SetFont('Arial', 'B', 12);
        $this->Cell(0, 10, $label, 1, 1, 'L', true);
        $this->Ln(2);
    }
}

$pdf = new ReportPDF();
$pdf->AliasNbPages();
$pdf->AddPage();

// Report Info
$pdf->SectionHeader('REPORT INFORMATION');
$pdf->SetFont('Arial', 'B', 11);
$pdf->Cell(40, 8, 'Report ID:', 0); $pdf->SetFont('Arial', '', 11); $pdf->Cell(0, 8, $report['report_id'], 0, 1);
$pdf->SetFont('Arial', 'B', 11);
$pdf->Cell(40, 8, 'Report Type:', 0); $pdf->SetFont('Arial', '', 11); $pdf->Cell(0, 8, $report['report_type'], 0, 1);
$pdf->SetFont('Arial', 'B', 11);
$pdf->Cell(40, 8, 'Period:', 0); $pdf->SetFont('Arial', '', 11); 
$period = date('M d, Y', strtotime($report['start_date'])) . ' to ' . date('M d, Y', strtotime($report['end_date']));
$pdf->Cell(0, 8, $period, 0, 1);
$pdf->SetFont('Arial', 'B', 11);
$pdf->Cell(40, 8, 'Generated By:', 0); $pdf->SetFont('Arial', '', 11); $pdf->Cell(0, 8, $report['generated_by'], 0, 1);
$pdf->Ln(5);

// Summary Data
$pdf->SectionHeader('SUMMARY STATISTICS');
$summaryData = $reportData['summary'] ?? ($reportData['data']['summary'] ?? null);

if ($summaryData) {
    foreach ($summaryData as $key => $value) {
        $label = ucwords(str_replace('_', ' ', $key));
        $pdf->SetFont('Arial', 'B', 11);
        $pdf->Cell(60, 8, $label . ':', 0);
        $pdf->SetFont('Arial', '', 11);
        $pdf->Cell(0, 8, $value, 0, 1);
    }
} else {
    $pdf->SetFont('Arial', 'I', 11);
    $pdf->Cell(0, 8, 'No summary data available.', 0, 1);
}
$pdf->Ln(5);

// Visit Details (if available)
if (isset($reportData['details']['visits']) && !empty($reportData['details']['visits'])) {
    $pdf->SectionHeader('VISIT DETAILS');
    $pdf->SetFont('Arial', 'B', 10);
    $pdf->Cell(40, 8, 'Date', 1);
    $pdf->Cell(50, 8, 'Patient', 1);
    $pdf->Cell(50, 8, 'Complaint', 1);
    $pdf->Cell(50, 8, 'Diagnosis', 1);
    $pdf->Ln();
    
    $pdf->SetFont('Arial', '', 9);
    foreach ($reportData['details']['visits'] as $visit) {
        $date = date('M d, Y', strtotime($visit['visit_date']));
        $name = $visit['first_name'] . ' ' . $visit['last_name'];
        
        // Handle long text wrapping
        $x = $pdf->GetX();
        $y = $pdf->GetY();
        
        $pdf->Cell(40, 8, $date, 1);
        $pdf->Cell(50, 8, substr($name, 0, 25), 1);
        $pdf->Cell(50, 8, substr($visit['chief_complaint'], 0, 30), 1);
        $pdf->Cell(50, 8, substr($visit['diagnosis'], 0, 30), 1);
        $pdf->Ln();
    }
}

// Medicine Usage Breakdown
if (isset($reportData['trends']['medicine_usage']) && !empty($reportData['trends']['medicine_usage'])) {
    $pdf->SectionHeader('MEDICINE USAGE BREAKDOWN');
    $pdf->SetFont('Arial', 'B', 10);
    $pdf->Cell(140, 8, 'Medicine Name', 1);
    $pdf->Cell(50, 8, 'Units Used', 1);
    $pdf->Ln();
    
    $pdf->SetFont('Arial', '', 9);
    foreach ($reportData['trends']['medicine_usage'] as $usage) {
        $pdf->Cell(140, 8, htmlspecialchars($usage['medicine_name'] ?? 'N/A'), 1);
        $pdf->Cell(50, 8, number_format($usage['total_used'] ?? 0), 1);
        $pdf->Ln();
    }
    $pdf->Ln(5);
}

$pdf->Output('D', 'Clinic_Report_' . $report_id . '.pdf');
?>