<?php
session_start();
require_once "../auth/auth_check.php";
require_once "../auth/database.php";
require_once "services/ClinicReportService.php";

$database = Database::getInstance();
$db = $database->getConnection();

if ($db === null || !isset($_GET['report_id'])) {
    die("Invalid request.");
}

$reportService = new ClinicReportService($db);
$report = $reportService->getReport($_GET['report_id']);

if (!$report) {
    die("Report not found.");
}

$report_data = json_decode($report['report_data'], true);
$filename = $report['report_id'] . ".csv";

// Set headers for CSV download
header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename=' . $filename);

$output = fopen('php://output', 'w');

// 1. Report Header
fputcsv($output, ['BCP CLINIC REPORT']);
fputcsv($output, ['Report ID:', $report['report_id']]);
fputcsv($output, ['Report Type:', $report['report_type']]);
fputcsv($output, ['Period:', $report['start_date'] . ' to ' . $report['end_date']]);
fputcsv($output, ['Generated By:', $report['generated_by']]);
fputcsv($output, ['Date Generated:', $report['created_at']]);
fputcsv($output, []); // Empty line

// 2. Summary Statistics
if (isset($report_data['summary'])) {
    fputcsv($output, ['SUMMARY STATISTICS']);
    foreach ($report_data['summary'] as $key => $value) {
        fputcsv($output, [ucwords(str_replace('_', ' ', $key)), $value]);
    }
    fputcsv($output, []);
}

// 3. Visit Details
if (isset($report_data['details']['visits']) && !empty($report_data['details']['visits'])) {
    fputcsv($output, ['PATIENT VISIT DETAILS']);
    fputcsv($output, ['Time', 'Patient Name', 'Chief Complaint', 'Diagnosis']);
    
    foreach ($report_data['details']['visits'] as $visit) {
        $time = isset($visit['visit_time']) ? $visit['visit_time'] : (isset($visit['visit_date']) ? date('h:i A', strtotime($visit['visit_date'])) : 'N/A');
        $name = ($visit['first_name'] ?? '') . ' ' . ($visit['last_name'] ?? '');
        fputcsv($output, [
            $time,
            $name,
            $visit['chief_complaint'] ?? 'N/A',
            $visit['diagnosis'] ?? 'N/A'
        ]);
    }
    fputcsv($output, []);
}

// 4. Common Diagnoses
if (isset($report_data['trends']['common_diagnoses']) && !empty($report_data['trends']['common_diagnoses'])) {
    fputcsv($output, ['TOP DIAGNOSES']);
    fputcsv($output, ['Diagnosis', 'Count']);
    foreach ($report_data['trends']['common_diagnoses'] as $diag) {
        fputcsv($output, [$diag['diagnosis'] ?? 'N/A', $diag['count'] ?? 0]);
    }
    fputcsv($output, []);
}

// 5. Medicine Usage Breakdown
if (isset($report_data['trends']['medicine_usage']) && !empty($report_data['trends']['medicine_usage'])) {
    fputcsv($output, ['MEDICINE USAGE BREAKDOWN']);
    fputcsv($output, ['Medicine Name', 'Units Used']);
    foreach ($report_data['trends']['medicine_usage'] as $usage) {
        fputcsv($output, [$usage['medicine_name'] ?? 'N/A', $usage['total_used'] ?? 0]);
    }
}

fclose($output);
exit;
